name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install Requirements
        run: python3 -m pip install -r requirements.txt

      - name: Deploy Pages
        run: python3 -m mkdocs gh-deploy --force
